/*
Session A
PROFIT ANALYSIS
1. Within the space of the last three years, what was the profit worth of the breweries,
inclusive of the anglophone and the francophone territories?
2. Compare the total profit between these two territories in order for the territory manager,
Mr. Stone made a strategic decision that will aid profit maximization in 2020.
3. Country that generated the highest profit in 2019
4. Help him find the year with the highest profit.
5. Which month in the three years was the least profit generated?
6. What was the minimum profit in the month of December 2018?
7. Compare the profit in percentage for each of the month in 2019
8. Which particular brand generated the highest profit in Senegal?
*/

-- 1. Within the space of the last three years, what was the profit worth of the breweries, inclusive of the anglophone and the francophone territories?
SELECT sum(profit) AS TotalProfit
FROM BREWERY
WHERE YEARS IN (2017, 2018, 2019);
-- the total profit generated by the company in the last three years is $105,587,420


-- 2. Compare the total profit between these two territories in order for the territory manager, Mr. Stone made a strategic decision that will aid profit maximization in 2020.
SELECT SUM(profit) as anglophone_profit,(SELECT SUM(profit)
										FROM brewery
										WHERE countries in ('Senegal','Togo','Benin')) as Francophone_profit
FROM BREWERY
WHERE countries in ('Nigeria','Ghana')
-- The total profit from anglophone countries is $42,389,260 while that of Francophone countries is $63,198,160


-- 3. Country that generated the highest profit in 2019
SELECT COUNTRIES, SUM(PROFIT) AS TOTAL_PROFIT
FROM BREWERY
WHERE YEARS = 2019
GROUP BY 1
ORDER BY TOTAL_PROFIT DESC
LIMIT 1;
-- Ghana generated the most profit in 2019


-- 4. Help him find the year with the highest profit.
SELECT YEARS, SUM(PROFIT) AS totalProfit
FROM BREWERY
GROUP BY 1
ORDER BY totalProfit desc
LIMIT 1;
-- The brewery made the highest profit in the year 2017, when it made a total of $38,503,320


-- 5. Which month in the three years was the least profit generated?
SELECT MONTHS, YEARS, PROFIT
FROM BREWERY
WHERE YEARS IN (2019, 2018, 2017)
GROUP BY 1, 2, 3
ORDER BY PROFIT
LIMIT 1;
-- The brewery made the least profit in the month of December 2017.


-- 6. What was the minimum profit in the month of December 2018?
SELECT MONTHS, YEARS, MIN(PROFIT)
FROM BREWERY
WHERE MONTHS = 'December' and years = 2018
GROUP BY 1,2;
-- The minimum profit in december 2018 is $38,150


-- 7. Compare the profit in percentage for each of the month in 2019
select months, years,  sum(profit), (sum(profit)*100)/(select sum(profit) from brewery where years = 2019) as percent_profit								
from brewery
where years = 2019
group by 1, 2
order by 4 desc;
-- This shows the percentage of profit each month of the year 2019

													 
-- 8. Which particular brand generated the highest profit in Senegal?
SELECT brands, countries, sum(profit)
from brewery
where countries = 'Senegal'
group by 1, 2
order by 3 desc
limit 1;


/*
Session B
BRAND ANALYSIS
1. Within the last two years, the brand manager wants to know the top three brands
consumed in the francophone countries
2. Find out the top two choice of consumer brands in Ghana
3. Find out the details of beers consumed in the past three years in the most oil reached
country in West Africa.
4. Favorites malt brand in Anglophone region between 2018 and 2019
5. Which brands sold the highest in 2019 in Nigeria?
6. Favorites brand in South_South region in Nigeria
7. Bear consumption in Nigeria
8. Level of consumption of Budweiser in the regions in Nigeria
9. Level of consumption of Budweiser in the regions in Nigeria in 2019 (Decision on Promo)
*/

-- 1. Within the last two years, the brand manager wants to know the top three brands consumed in the francophone countries
SELECT brands, SUM(quantity) as Purchased_quantity
FROM brewery
WHERE countries in ('Senegal','Togo','Benin') and years in (2019, 2018)
GROUP BY Brands
ORDER BY 2 desc
LIMIT 3;
-- The top three brands in Francophone countries are trophy, hero and eagle lager.


-- 2. Find out the top two choice of consumer brands in Ghana
select brands, sum(quantity) as Total_purchased
from brewery
where countries = 'Ghana'
group by 1
order by Total_purchased desc
limit 2;
-- The top two brands in Ghana are eagle lager and castle lite


-- 3. Find out the details of beers consumed in the past three years in the most oil reached country in West Africa.
select years, brands, unit_price, sum(quantity) as total_Quantity, sum(cost) as total_Cost
from brewery
where countries = 'Nigeria' and brands not like '%malt%'
group by 1,2,3
order by 1,4;
-- The table shows the beer brands in Nigeria and yearly consumption quantity of beers


-- 4. Favorites malt brand in Anglophone region between 2018 and 2019
SELECT brands, SUM(quantity) as Purchased_quantity
FROM brewery
WHERE countries in ('Nigeria','Ghana') and years in (2019, 2018) and brands like '%malt%'
GROUP BY Brands
ORDER BY 2 desc;
-- The favourite malt brand in the Anglophone region is grand malt


-- 5. Which brands sold the highest in 2019 in Nigeria?
select brands, sum(quantity) as Total_Quantity
from brewery
where countries = 'Nigeria' and Years = 2019
group by brands
order by Total_Quantity desc
limit 2;
-- Hero sold the highest in 2019


-- 6. Favorites brand in South_South region in Nigeria
select brands, region, countries, sum(quantity) as total_quantity
from brewery
where region = 'southsouth' and countries = 'Nigeria'
group by 1, 2, 3
order by 4 desc
limit 3;
-- The favourite brand in the south-south region in Nigeria is eagle lager


-- 7. Beer consumption in Nigeria
select countries, sum(quantity) as total_purchased
from brewery
where countries = 'Nigeria' and brands not like '%malt%'
group by 1;
-- The beer consumption in Nigeria by quantity is 129,260 units


-- 8. Level of consumption of Budweiser in the regions in Nigeria
select brands, region, countries, sum(quantity) as quantity
from brewery
where countries = 'Nigeria' and brands = 'budweiser'
group by 1, 2, 3
order by quantity desc;
-- This returns the quantity of budweiser consumed by various regions in Nigeria


-- 9. Level of consumption of Budweiser in the regions in Nigeria in 2019 (Decision on Promo)
select brands, region, countries, sum(quantity) as quantity
from brewery
where countries = 'Nigeria' and brands = 'budweiser' and years = 2019
group by 1, 2, 3
order by quantity desc;
/* the higest quantity of budweiser is in the southeast region, the southsouth 
and west have relatively lower quantities, the company should consider increasing their promotions in those regions
*/



/*Session C
COUNTRIES ANALYSIS
1. Country with the highest consumption of beer.
2. Highest sales personnel of Budweiser in Senegal
3. Country with the highest profit of the fourth quarter in 2019
*/

-- 1. Country with the highest consumption of beer.
select countries, sum(quantity) as total_quantity
from brewery
where brands not like '%malt%'
group by 1
order by 2 desc
limit 1;
-- Senegal is the country with the highest beer consumption


-- 2. Highest sales personnel of Budweiser in Senegal
select sales_rep, brands, sum(quantity) as total_quantity
from brewery
where brands = 'budweiser' and countries = 'Senegal'
group by 1, 2
order by 3 desc
limit 1;
-- The higest sale personnel in Senegal is Jones who has sold a sum of 5917 units


-- 3. Country with the highest profit of the fourth quarter in 2019
select countries, sum(quantity) as forth_quarter_total
from brewery
where months in ('October', 'November', 'December') and years = 2019
group by 1
order by 2 desc
limit 1;
-- Ghana made the highest profit in the forth quater in 2019
	
